apiVersion: apps/v1
kind: Deployment

metadata:
  name: ticket-backend

spec:
  replicas: 1

  selector:
    matchLabels:
      app: ticket-backend

  template:
    metadata:
      labels:
        app: ticket-backend

    spec:
      containers:
      - name: ticket-backend
        image: mudasir18/ticket-backend:v1

        ports:
        - containerPort: 5000

        env:
        - name: DB_HOST
          value: "mariadb"

        - name: DB_USER
          value: "ticketuser"

        - name: DB_PASSWORD
          value: "ticket123"

        - name: DB_NAME
          value: "ticket_system"
